 - name: Ceramic Tile Design
   description: 
 - name: Value Engineering
   description: 
 - name: Flooring Demolition
   description: 
 - name: Floor Preparation
   description: 
 - name: Waterproofing and Anti Fracture Membranes
   description: 
 - name: Heated Flooring
   description: 
 - name: Ceramic/Porcelain Tile Installation
   description: 
 - name: Quarry Tile Installation
   description: 
 - name: Terrazzo/Stone Tile Installation
   description: 
 - name: Setting Beds (Dry Pack)
   description: 
 - name: Epoxy Grout
   description: 
 - name: Thin Brick and Stone Veneer
   description: 